# Unit 17 — LO4: Designing a Data Science Solution for a Business Problem

An assessment-oriented notebook that brings the previous analytical techniques together into an end-to-end solution design.

## Learning Objectives
- Define a real business problem and SMART objective.
- Identify stakeholders and requirements.
- Define KPIs and data requirements.
- Map current and proposed business processes.
- Design an end-to-end data-science workflow.
- Plan implementation and testing.
- Evaluate the solution against requirements.
- Produce justified business recommendations.

## Prerequisites
- All previous Unit 17 data-analysis notebooks
- Pandas/NumPy/EDA
- Basic visualisation
- Business-process understanding

## Class Delivery
Approx. 60 minutes for guided teaching, followed by an extended student design/project activity.

> **Teaching pattern:** explain the concept → demonstrate → interpret → practise → connect to a business decision.

## 1. What Changes in LO4?

Earlier lessons focused on individual techniques:

- file handling
- NumPy
- Pandas
- EDA
- visualisation
- data mining
- external data collection
- forecasting

LO4 asks a different question:

> **Can you use those techniques together to support a real business problem?**

The Unit 17 assessment criteria include:

- designing a data-science solution
- implementing the solution
- making justified recommendations

So LO4 is about **end-to-end problem solving**, not learning another Python library.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
plt.rcParams["figure.figsize"] = (10, 5)

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.5.4
Pandas: 3.0.6

## 2. Business Problem vs Technical Problem

### Business problem

> Customer repeat purchases are falling.

### Technical question

> Which customer behaviours are associated with low repeat-purchase activity?

### Data-science task

> Collect, prepare and analyse customer transaction data to identify patterns and produce recommendations.

Students should always start with the **business problem**, not the code.

## 3. Define the Problem Clearly

A good problem statement should identify:

- organisation/context
- problem
- affected area
- desired outcome
- time period or scope

### Weak

> Analyse customer data.

### Strong

> An e-commerce business has seen a decline in repeat purchases over the last six months and wants to identify customer groups with reduced activity and the factors associated with the decline.

## 4. Define SMART Objectives

Students can use:

- Specific
- Measurable
- Achievable
- Relevant
- Time-bound

Example:

> Analyse six months of customer transaction data to identify segments with low repeat-purchase activity and recommend actions that could support retention.

## 5. Stakeholder Identification

Typical stakeholders:

| Stakeholder | Interest |
|---|---|
| Senior management | Business outcome |
| Marketing manager | Customer segments and campaigns |
| Sales manager | Revenue and customers |
| Data analyst | Analysis quality |
| IT / developer | Data pipeline and implementation |
| Customer service | Customer experience |

In [2]:
stakeholders = pd.DataFrame({
    "stakeholder": [
        "Senior Management",
        "Marketing Manager",
        "Sales Manager",
        "Data Analyst",
        "IT / Developer"
    ],
    "needs": [
        "Business impact and recommendation",
        "Segments and campaign opportunities",
        "Customer and revenue performance",
        "Reliable analysis and evidence",
        "Feasible implementation"
    ]
})

stakeholders

         stakeholder                                needs
0  Senior Management   Business impact and recommendation
1  Marketing Manager  Segments and campaign opportunities
2      Sales Manager     Customer and revenue performance
3       Data Analyst       Reliable analysis and evidence
4     IT / Developer              Feasible implementation

## 6. Requirements

### Business requirements

What the organisation needs to achieve.

### User requirements

What a user needs from the solution.

### Data requirements

What data is needed.

### System requirements

What the system/tool must provide.

Example:

| Type | Requirement |
|---|---|
| Business | Improve retention decision making |
| User | Manager can identify low-activity customers |
| Data | Customer ID, date, transaction value and category |
| System | Generate repeatable monthly analysis |

## 7. KPI Definition

A solution should define how success is measured.

Possible KPIs:

- revenue
- order count
- average order value
- repeat-purchase rate
- active customers
- retention rate
- forecast error
- processing time

### Important

A KPI is useful only when:

1. it relates to the business objective
2. the data required is available
3. the result can influence a decision.

In [3]:
kpi_framework = pd.DataFrame({
    "KPI": ["Revenue", "Average Order Value", "Repeat Purchase Rate", "Active Customers"],
    "Definition": [
        "Total sales value",
        "Revenue divided by number of orders",
        "Share of customers with more than one purchase",
        "Customers with at least one purchase in the period"
    ],
    "Decision_use": [
        "Monitor commercial performance",
        "Assess customer value",
        "Monitor retention",
        "Monitor engagement"
    ]
})

kpi_framework

                    KPI                                         Definition                    Decision_use
0               Revenue                                  Total sales value  Monitor commercial performance
1   Average Order Value                Revenue divided by number of orders           Assess customer value
2  Repeat Purchase Rate     Share of customers with more than one purchase               Monitor retention
3      Active Customers  Customers with at least one purchase in the pe...              Monitor engagement

## 8. Current Business Process

A business-process view might be:

```text
Customer
   ↓
Purchase
   ↓
Transaction System
   ↓
Stored Data
   ↓
Manual Report
   ↓
Manager Review
   ↓
Decision
```

Students should identify:

- bottlenecks
- manual steps
- duplicated work
- data-quality risks
- opportunities for automation

## 9. Proposed Data-Supported Process

```text
Customer
   ↓
Purchase
   ↓
Transaction System
   ↓
Data Collection
   ↓
Validation / Cleaning
   ↓
Analysis / Data Mining
   ↓
Visualisation / Report
   ↓
Manager Decision
   ↓
Business Action
```

## 10. Solution Architecture

A simple architecture:

```text
Data Sources
    ↓
Collection
    ↓
Raw Data
    ↓
Cleaning / Validation
    ↓
Analysis
    ↓
Data Mining / Forecasting
    ↓
Visualisation
    ↓
Business Recommendation
    ↓
Stakeholder
```

Students should be able to explain where each technology fits.

In [4]:
solution_components = pd.DataFrame({
    "Stage": [
        "Data Source",
        "Collection",
        "Preparation",
        "Analysis",
        "Output",
        "Decision"
    ],
    "Possible Tool": [
        "CSV / API / Database",
        "Python / requests",
        "Pandas / NumPy",
        "Pandas / data mining / forecasting",
        "Matplotlib / report",
        "Manager / business team"
    ]
})

solution_components

         Stage                       Possible Tool
0  Data Source                CSV / API / Database
1   Collection                   Python / requests
2  Preparation                      Pandas / NumPy
3     Analysis  Pandas / data mining / forecasting
4       Output                 Matplotlib / report
5     Decision             Manager / business team

## 11. Data Quality Risks

A good design explicitly identifies risks.

Examples:

- missing values
- duplicate records
- incorrect dates
- inconsistent categories
- delayed data
- inaccurate source systems
- biased samples
- external data changes

### Risk principle

> **A sophisticated analysis built on poor data can still produce poor decisions.**

## 12. Example End-to-End Case

### Business

An online retailer wants to understand why sales have become more volatile and whether competitor prices may be affecting performance.

### Available data

- internal sales CSV
- product master data
- competitor price data from an approved source
- monthly sales history

### Goal

Produce evidence and recommendations for pricing and inventory decisions.

In [5]:
# Create a small case-study dataset
case_sales = pd.DataFrame({
    "month": pd.date_range("2025-01-01", periods=12, freq="MS"),
    "sales": [120, 125, 130, 128, 135, 142, 139, 136, 145, 151, 160, 168],
    "competitor_avg_price_index": [100, 99, 98, 99, 97, 96, 97, 98, 96, 95, 94, 94]
})

case_sales

        month  sales  competitor_avg_price_index
0  2025-01-01    120                         100
1  2025-02-01    125                          99
2  2025-03-01    130                          98
3  2025-04-01    128                          99
4  2025-05-01    135                          97
5  2025-06-01    142                          96
6  2025-07-01    139                          97
7  2025-08-01    136                          98
8  2025-09-01    145                          96
9  2025-10-01    151                          95
10 2025-11-01    160                          94
11 2025-12-01    168                          94

## 13. Solution Workflow for the Case

Students can combine:

1. data validation
2. EDA
3. relationship analysis
4. simple forecasting
5. external price comparison
6. visualisation
7. recommendation

Notice that no machine-learning model is required to demonstrate the idea of an end-to-end data-science solution.

In [6]:
case_sales["sales_change_pct"] = case_sales["sales"].pct_change() * 100
case_sales["price_change_pct"] = case_sales["competitor_avg_price_index"].pct_change() * 100

case_sales

        month  sales  competitor_avg_price_index  sales_change_pct  price_change_pct
0  2025-01-01    120                         100               NaN               NaN
1  2025-02-01    125                          99          4.166667         -1.000000
2  2025-03-01    130                          98          4.000000         -1.010101
3  2025-04-01    128                          99         -1.538462          1.020408
4  2025-05-01    135                          97          5.468750         -2.020202
5  2025-06-01    142                          96          5.185185         -1.030928
6  2025-07-01    139                          97         -2.112676          1.041667
7  2025-08-01    136                          98         -2.158273          1.030928
8  2025-09-01    145                          96          6.617647         -2.040816
9  2025-10-01    151                          95          4.137931         -1.041667
10 2025-11-01    160                          94          5.960265         -1.052632
11 2025-12-01    168                          94          5.000000          0.000000

## 14. Implementation Plan

Students should state:

- what will be built
- which data is needed
- which tools will be used
- what outputs will be produced
- who will use the result
- when the solution will run
- how the solution will be maintained

In [7]:
implementation_plan = pd.DataFrame({
    "Step": [
        1, 2, 3, 4, 5, 6
    ],
    "Activity": [
        "Collect source data",
        "Validate and clean data",
        "Perform EDA",
        "Run analysis / forecasting",
        "Generate report / visualisation",
        "Review recommendations"
    ],
    "Owner": [
        "Analyst",
        "Analyst",
        "Analyst",
        "Analyst",
        "Analyst / Developer",
        "Business Manager"
    ]
})

implementation_plan

   Step                         Activity                Owner
0     1              Collect source data              Analyst
1     2          Validate and clean data              Analyst
2     3                      Perform EDA              Analyst
3     4       Run analysis / forecasting              Analyst
4     5  Generate report / visualisation  Analyst / Developer
5     6           Review recommendations     Business Manager

## 15. Testing

Do not finish when the code runs.

Test:

- inputs
- missing data
- incorrect types
- unexpected values
- outputs
- calculations
- visualisations
- requirement fulfilment

A simple test table:

| Requirement | Test | Expected | Result |
|---|---|---|---|
| Load sales data | Valid CSV | DataFrame created | Pass |
| Handle missing value | Insert missing price | Missing value flagged | Pass |
| Calculate revenue | Known example | Correct value | Pass |
| Produce output | Run report | Report generated | Pass |

In [8]:
test_cases = pd.DataFrame({
    "requirement": [
        "Load sales data",
        "Handle missing price",
        "Calculate revenue",
        "Generate output"
    ],
    "test": [
        "Provide valid CSV",
        "Insert missing price",
        "Use known quantity × price example",
        "Run analysis end-to-end"
    ],
    "expected": [
        "DataFrame created",
        "Value detected/flagged",
        "Correct calculation",
        "Output produced"
    ],
    "status": ["Pass", "Pass", "Pass", "Pass"]
})

test_cases

            requirement                                test                expected status
0       Load sales data                   Provide valid CSV       DataFrame created   Pass
1  Handle missing price                Insert missing price  Value detected/flagged   Pass
2     Calculate revenue  Use known quantity × price example     Correct calculation   Pass
3       Generate output             Run analysis end-to-end         Output produced   Pass

## 16. Evaluate Against Requirements

For D2-style evaluation, students should compare the solution against:

### User requirements
Can the user understand and use it?

### Business requirements
Does it support the original decision?

### Data quality
Is the evidence reliable enough?

### Technical feasibility
Can it be repeated and maintained?

### Risks
What could make the result wrong or misleading?

## 17. Recommendation Framework

A justified recommendation should contain:

**Evidence → Meaning → Business impact → Action → Expected benefit → Risk/limitation**

Example:

> Competitor prices were consistently below our prices for two key products. This indicates that our current pricing may reduce competitiveness in those products. Management should review pricing for these products while checking margin constraints. The recommendation should be monitored using sales volume and margin KPIs.

## 18. Student Design Exercise

### Scenario

A supermarket wants to improve promotion decisions.

Students must design a data-science solution.

They must submit:

1. problem statement
2. stakeholders
3. business requirements
4. data requirements
5. KPIs
6. current process
7. proposed process
8. data-science workflow
9. tool choice
10. expected output
11. testing approach
12. risks
13. final recommendation format

In [9]:
# Student LO4 design template
solution_design = {
    "problem": "",
    "stakeholders": [],
    "business_requirements": [],
    "user_requirements": [],
    "data_requirements": [],
    "kpis": [],
    "current_process": [],
    "proposed_process": [],
    "data_sources": [],
    "techniques": [],
    "outputs": [],
    "tests": [],
    "risks": [],
    "recommendations": []
}

solution_design

{'problem': '',
 'stakeholders': [],
 'business_requirements': [],
 'user_requirements': [],
 'data_requirements': [],
 'kpis': [],
 'current_process': [],
 'proposed_process': [],
 'data_sources': [],
 'techniques': [],
 'outputs': [],
 'tests': [],
 'risks': [],
 'recommendations': []}

## 19. Requirement Traceability Matrix

A useful final technique is to connect each requirement to an implementation/test.

```text
Requirement
    ↓
Data
    ↓
Analysis
    ↓
Output
    ↓
Test
    ↓
Business Decision
```

In [10]:
traceability = pd.DataFrame({
    "Requirement": [
        "Manager needs regional sales comparison",
        "Manager needs monthly trend",
        "Manager needs recommendation"
    ],
    "Data": [
        "region, revenue",
        "date, revenue",
        "analysis outputs"
    ],
    "Technique": [
        "groupby + comparison",
        "time-series analysis",
        "business interpretation"
    ],
    "Output": [
        "regional chart",
        "trend/forecast chart",
        "recommendation section"
    ],
    "Test": [
        "Check totals against source",
        "Check date ordering",
        "Check recommendation has evidence"
    ]
})

traceability

,Requirement,Data,Technique,Output,Test
0,Manager needs regional sales comparison,"region, revenue",groupby + comparison,regional chart,Check totals against source
1,Manager needs monthly trend,"date, revenue",time-series analysis,trend/forecast chart,Check date ordering
2,Manager needs recommendation,analysis outputs,business interpretation,recommendation section,Check recommendation has evidence

## 20. Final LO4 Checklist

### Problem
- Is the business problem specific?

### Requirements
- Are user and business requirements clear?

### Data
- Are the data sources appropriate?
- Are quality risks identified?

### Analysis
- Does the analysis answer the business question?

### Output
- Is the output meaningful to the intended user?

### Testing
- Was the solution tested?

### Evaluation
- Does it actually meet the requirements?

### Recommendation
- Is the recommendation justified by evidence?

### Limitations
- Are assumptions and risks explained?

## 21. Mini End-to-End Challenge

### Case

An e-commerce company wants to reduce stock-outs and improve promotion decisions.

### Student task

Design a solution that:

1. defines the problem
2. identifies stakeholders
3. defines requirements
4. identifies data sources
5. proposes data collection
6. validates and analyses historical data
7. uses data mining or forecasting where appropriate
8. visualises the results
9. produces recommendations
10. defines tests
11. evaluates the solution against the requirements

### Important

The goal is not the largest amount of code.

The goal is a **clear, justified business solution**.

## 22. Summary — From Tools to Solution

Students now have a complete progression:

```text
Python
   ↓
File Handling
   ↓
NumPy
   ↓
Pandas
   ↓
EDA
   ↓
Visualisation
   ↓
Data Mining
   ↓
Web/API Data
   ↓
Forecasting
   ↓
Business Insight
   ↓
LO4 Solution Design
   ↓
Recommendation
```

Machine learning can now be introduced naturally in the next unit as another analytical technique inside this larger workflow.

## 23. Suggested Final Student Deliverable

A concise final business pack can contain:

1. Business problem
2. Stakeholders
3. Requirements
4. Data sources
5. Data preparation summary
6. Analysis
7. Visualisations
8. Data-mining/forecasting findings
9. Business impact
10. Recommendation
11. Testing
12. Evaluation
13. Limitations
14. Next steps

This structure can be reused for the Unit 17 assignment and adapted when machine learning is introduced in the next unit.